### ISSUE TITLE
Make user automatically return to parq after navigating

### ISSUE THREAD

**Issue by kenzshelley** [parq-app/parq-android#7]
Right now the user has to come back to parq by themselves when they finish navigation. 

There might be a way to make this automatic by monitoring the notifications center, and returning to parq once google maps no longer has an item there. Unsure.

**Comment by nickcharles** [comment]
I don't know much about implicit intents, but it looks like this might be what we're looking for?

http://developer.android.com/training/basics/intents/result.html

**Comment by kenzshelley** [comment]
So the activity that you're calling gets to decide what result to return & when -- Google maps doesn't return a result (at least that's what my googling seemed to indicate), so unfortunately all we know is when the user manually leaves Google maps & comes back to parq, not when the user actually finishes navigation.

**Comment by kenzshelley** [comment]
I don't think this is actually worth pursuing -- It seems like there's not really going to be a good way to do it, and regardless it's not something that we'll be able to demo easily. Closin for now
